[package]
name = "lnp-core"
version = "0.3.0-beta.1"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "LNP Core Library: rust implementation of modular lightning channels architecture"
repository = "https://github.com/LNP-BP/lnp-core"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2018"
exclude = [".github", "contrib"]

[lib]
name = "lnp"
path = "src/lib.rs"
crate-type = ["dylib", "rlib", "staticlib"]

# Dependencies
# ============
#
# Version policy
# --------------
# The policy in specifying dependencies versions are to use tilde requirements
# according to
# <https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html?highlight=feature#tilde-requirements>
# with full semver version specification (major, minor and patch components)
# which means that we may upgrade for patches/bugfixes, but must not change
# even the minor version of the package.
# Once the library is stable consider upgrading tilde requirements to strict
# equivalence requirements (with '=' sign) since even dependencies patching will
# not introduce risk of breaking the consensus and even security updates must
# be done manually after through testing
[dependencies]
# Dependencies on other LNP/BP repositories
# -----------------------------------------
amplify = { version = "2.4", features = ["stringly_conversions"] }
amplify_derive = "2.4.3"
strict_encoding = { version = "1.0.0-rc.3", features = ["miniscript"] }
strict_encoding_derive = "1.0.0-rc.1"
client_side_validation = "1.0.0-rc.2"
# Dependencies on core rust-bitcoin ecosystem projects
# ----------------------------------------------------
bitcoin = { version = "~0.26.0", features = ["rand"] }
bitcoin_hashes = "~0.9.4" # we need macro from here
bech32 = "~0.7.2"
# Core rust projects
# ------------------
#   This strange naming is a workaround for cargo inability to define required
#   features for a dependency. See
#   <https://github.com/rust-lang/api-guidelines/issues/180> for the explanation
#   and references.
serde_crate = { package = "serde", version = "~1.0.106", features = ["derive"], optional = true }
serde_with = { version = "~1.5.1", features = ["hex"], optional = true }
serde_with_macros = { version = "~1.2.0", optional = true } # Fix for the problem in 1.3.0
lazy_static = "~1.4.0"
# Serializtion
# ------------
#    Used in RGB data Bech32 encodings
regex = "1"
# Temporary-needed dependencies:
# ------------------------------
# 2. We use these to simplify enum strict encoding, but once the required
#    functionality will become part of either amplify_derive or lnpbp_derive
#    crates they should be removed
num-traits = "~0.2.11"
num-derive = "~0.3.0"

[dev-dependencies]
serde_json = "~1.0.60"

# Features
# ========
[features]
# Listings
# --------
#   By default we use LNP with Tor support and URL support
default = []
all = ["serde"]
serde = ["serde_crate", "serde_with", "serde_with_macros", "amplify/serde",
         "bitcoin/use-serde", "bitcoin_hashes/serde"]

[workspace]
members = ["."]
default-members = ["."]
exclude = ["dep_test"]
