[package]
name = "lnp-core"
version = "0.4.0-rc.1"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "LNP Core Library: rust implementation of modular lightning channels architecture"
repository = "https://github.com/LNP-BP/lnp-core"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2018"
exclude = [".github", "contrib", "lightning_encoding", "lnp2p"]

[lib]
name = "lnp"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
amplify = "3.9.1"
strict_encoding = "1.7.2"
lightning_encoding = { version = "0.5.0-beta.2", path = "./lightning_encoding" }
descriptor-wallet = { version = "0.5.0-alpha.3", features = ["keygen"] }
lnpbp = "0.5.0-beta.3"
rgb-core = { version = "0.5.0-alpha.1", optional = true, path = "../../rgb/rgb-core" }
bitcoin = { version = "0.27", features = ["rand"] }
secp256k1 = { version = "0.20.3", features = ["global-context-less-secure"] }
internet2 = "0.5.0-alpha.1"
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
serde_with = { version = "1.8", features = ["hex"], optional = true }
lazy_static = "1.4"

[features]
default = []
all = ["rgb", "serde"]
rgb = ["rgb-core"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde"]

[workspace]
members = [".", "lightning_encoding", "lightning_encoding/derive"] #, "lnp2p", ]
default-members = [".", "lightning_encoding", "lightning_encoding/derive"] #, "lnp2p", ]
exclude = ["dep_test"]
